### PR TITLE
Don't reset table and referee fields, closes #164

### LINKED ISSUE #164: Remember table and referee on score submission

### PR DESCRIPTION
**Pull request by rikkertkoppes**
@poelstra can you give a quick review. May be a nice addition for tomorrow.

### CODE REVIEW

**Comment by Jheronymus** [comment]
So you removed the clear for the ref and field from the save function. Could you clarify the behavior now? It only gets reset when the controller initiates right? In what cases does that happen?

**Comment by rikkertkoppes** [comment]
The controller initializes when the page is loaded / refreshed. So never during normal operation. Of course you can manually change the dropdowns at any time still.

**Comment by poelstra** [comment]
In fact there are 2 clear operations:
* an implicit one on submit
* an explicit one when the user clicks the reset button

I think it would be better if the latter *does* clear referee and table.

In terms of more reliable code, I think it would make sense to let clear() always clear table and referee (thus all init logic is in one place), and temporarily store table and referee inside the submit handler (such that it can 'restore' it after the call to clear()).

Other than that, the commit looks fine to me.

**Comment by rikkertkoppes** [comment]
@Jheronymus @sleemans  what are your opinions here? (if there it a tie, we let @kmeesters weigh in)

I'd prefer the clear() button to not clear the table and referee (as I implemented). I would say that table and referee are not part of the scoresheet, but metadata about it.

**Comment by Jheronymus** [comment]
As a ref I think it would make more sense to discard the scoring info with the clear button (lets say in case of a match restart). If you had to fill in your name and table again, that would be a bit unexpected.

**Comment by poelstra** [comment]
Ok, then I guess it's better to leave it as @rikkertkoppes coded it.

:+1:

**Comment by sleemans** [comment]
I think it's a trade off and depends on the situation: If the ref passes the tablet on, it makes sense to clear the table and ref. If the ref only resets the scoresheet,  I would opt for keeping the ref and table.

I would agree with Rikkert and Jeroen: Let the clear button keep the referee and table as well; as that is the most occurring.
________________________________
Van: Jeroen<mailto:notifications@github.com>
Verzonden: ‎27-‎11-‎2015 16:58
Aan: FirstLegoLeague/fllscoring<mailto:fllscoring@noreply.github.com>
CC: Leemans, S.J.J.<mailto:s.j.j.leemans@tue.nl>
Onderwerp: Re: [fllscoring] Don't reset table and referee fields, closes #164 (#180)


As a ref I think it would make more sense to discard the scoring info with the clear button (lets say in case of a match restart). If you had to fill in your name and table again, that would be a bit unexpected.

**Pull request merged**
