### PR TITLE
added black bars error

### PR DESCRIPTION
**Pull request by sleemans**
The score sheet will give an error, unless the black bars in mission M04 count up to 12.

### CODE REVIEW

**Comment by sleemans** [comment]
Solving issue https://github.com/FirstLegoLeague/fllscoring/issues/166

**Comment by rikkertkoppes** [comment]
What happened? Thousands of lines changed? Not sure this is ok. Can you check?

**Comment by sleemans** [comment]
The only current option is to list all 12*8*12 options in the xml, and for each of them denote whether it’s an error or a score. For later use, a more elegant solution is advisable.

**Comment by rikkertkoppes** [comment]
Look into it. Apart from the code formatting, you are missing the * 8 * values. I would expect a total 81 valid combinations. I can only find 76, which accounts for the 5 combinations: 

    0 8 4
    1 8 3
    2 8 2
    3 8 1
    4 8 0

I this is resolved (or my premise turns out to be wrong), I am a happy to merge

**Comment by sleemans** [comment]
Correct, I missed the 8 values. Added now and corrected the indentation. Thanks :)

**Comment by sleemans** [comment]
The 8th cleaned-up black bar option was indeed missing. Has been added and the new cases have been properly indented.

**Comment by rikkertkoppes** [comment]
Changed tabs to spaces and merged. Please use spaces. We have a .editorconfig file for that. http://editorconfig.org/

**Pull request merged**
