### PR TITLE
added 'none' to M14

### PR DESCRIPTION
**Pull request by sleemans**
solves #210

### CODE REVIEW

**Comment by rikkertkoppes** [comment]
@sleemans there seem to be some conflicts, can you check on that and amend your PR?

**Comment by rikkertkoppes** [comment]
Great work keeping these bits up to date Sander! However, before I merge I want to make sure I fully understand the changes and verify these are as intended.

There now seem to be three versions of the scoring definitions. I assume this is intended, but what is the purpose of those three? Would it be an option to stick to just one version? If not, do we have some space to document the versions?

@kmeesters @Jheronymus @poelstra What are your thoughts on this?

**Comment by poelstra** [comment]
@rikkertkoppes hmmm, seem to recall the idea was to have one generic definition, and then some language-overrides of just the translatable parts. However, I don't really remember how that was supposed to work, so it could very well be that the way things currently stand, is the only way to have multiple languages right now?

I'm not sure what the reason for 'normal' and 'ref_optimised' is, maybe an XML comment can be added in them to explain?

While looking at the PR, I did notice it wasn't really clear what part is generated, and what part is 'real source'. I suppose it makes sense to either not put the generated files in Git, or at least move them into some kind of 'generated' subfolder.

Another thing I happened to notice, is that en_US_ref_optimised should probably either be en_UK_ref_optimised, or en_US_ref_optimized ;-p

**Comment by kmeesters** [comment]
Hi all, this is on purpose. We have some different requirements for the scoring sheets coming from different stakeholders. There is a scoresheet as close as possible to the original (paper) one, and one that that is designed to make better use of the fact that it is to be used on tablets. 

I'll add the comments in the XML to explain this more clearly in time. For now, please now that @sleemans and I have talked at length about this. There is some consideration for end user adaption  here :). More explanation on Slack.

Please merge this merge so I can update the demo's

**Pull request merged**
